### ISSUE TITLE
Execution failed for task ':mlsnode3:mlInit'

### ISSUE THREAD

**Issue by sjordan1975** [MarkLogicUniversity/OnDemand#1]
Following along on the tutorial.

Running the following command results in error

```
$> gradle deployApp
```

Error:
```
I/O error on POST request for "http://localhost:28001/admin/v1/init": Connect to localhost:28001 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused; nested exception is org.apache.http.conn.HttpHostConnectException: Connect to localhost:28001 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
```
Environment:
MarkLogic-9.0-2.x86_64.rpm
Docker 17.06.2-ce
OSX 10.11.6
Java 8

**Comment by alan-johnson** [comment]
Thank you for viewing the ml-gradle On Demand tutorial video. The key to this is the error message itself, "Connection refused". When ml-gradle creates the Docker cluster with the docker-compose commands, 3 containers are created with MarkLogic named "mls.node1", "mls.node2" and "mls.node3". The last one exposes MarkLogic's Admin Interface to the port 28001 outside of the container. So if the connection is refused, the container "mls.node3" either wasn't created or it's not started. You can look at the containers on your system with the command, `docker ps -a`. If the "mls.node3" container is created but not running, you can try starting the container with `docker start mls.node3`.  FYI, the README file specifically states that Docker 17.06.0-ce had an issue with docker-compose on the Mac. The ml-gradle code was specifically tested on Docker 17.03.0-ce. For versions later than that, it might or might not function as expected. Basically, it's a Docker issue, not an ml-gradle issue. We can help to narrow down the culprit but when it stops being a MarkLogic issue, there's not much we can do to fix it.
